### ISSUE TITLE
TODO/FIXME Count 8

### ISSUE THREAD

**Issue by mattcollier** [veres-one/did-veres-one#55]
- [ ] TODO: support methods that are not LDKeyPairs
       Commit: (73b11da) Change API names.
       File:  [lib/VeresOneDidDoc.js:450](https://github.com/veres-one/did-veres-one.git/blob/master/lib/VeresOneDidDoc.js#L450)
       Matthew Collier commented a year ago

  - [ ] TODO: Check for revocation and expiration
       Commit: (5f79655) Implement doc.suiteKeyNode(), use updated crypto-ld. (#19)
       File:  [lib/VeresOneDidDoc.js:275](https://github.com/veres-one/did-veres-one.git/blob/master/lib/VeresOneDidDoc.js#L275)
       Dmitri Zagidulin commented a year ago

  - [ ] TODO: update to use `(expires)` pseudo header or just use
       Commit: (b236096) Fix style.
       File:  [lib/VeresOneClient.js:214](https://github.com/veres-one/did-veres-one.git/blob/master/lib/VeresOneClient.js#L214)
       Matthew Collier commented 8 months ago

  - [ ] FIXME: the web-ledger-client 1.0 APIs need some refinement, possibly
       Commit: (f0d4fc0) Implement update operations.
       File:  [lib/VeresOneClient.js:203](https://github.com/veres-one/did-veres-one.git/blob/master/lib/VeresOneClient.js#L203)
       Matthew Collier commented a year ago

  - [ ] FIXME: currently unused, update this implementation after testnet v2
       Commit: (795de18) Use TypeError.
       File:  [lib/VeresOneClient.js:145](https://github.com/veres-one/did-veres-one.git/blob/master/lib/VeresOneClient.js#L145)
       Matthew Collier commented a year ago

  - [ ] FIXME - remove, replace with cache
       Commit: (aa51dcd) Add a forceConstruct override to get().
       File:  [lib/VeresOneClient.js:63](https://github.com/veres-one/did-veres-one.git/blob/master/lib/VeresOneClient.js#L63)
       Dmitri Zagidulin commented 2 months ago

  - [ ] TODO: support `signer` API as alternative to `privateKeyPem`
       Commit: (1ef270c) Extract VeresOne code from did-io.
       File:  [lib/veres-one.js:330](https://github.com/veres-one/did-veres-one.git/blob/master/lib/veres-one.js#L330)
       Dmitri Zagidulin commented 2 years ago

  - [ ] FIXME: validate didDocument, creator, and privateKeyPem
       Commit: (1ef270c) Extract VeresOne code from did-io.
       File:  [lib/veres-one.js:329](https://github.com/veres-one/did-veres-one.git/blob/master/lib/veres-one.js#L329)
       Dmitri Zagidulin commented 2 years ago
